_extends: teckshop:.github/release-drafter.yml
name-template: 'yarp-v$RESOLVED_VERSION'
tag-template: 'yarp-v$RESOLVED_VERSION'
tag-prefix: yarp-
include-paths:
  - "src/gateways/yarp"
  - "src/buildingblocks/"
  - "src/Directory.Packages.props"
  - "src/Directory.Build.props"
template: |
  ## What Changed 👀
  $CHANGES
