apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rabbitmq-pushsecret
  namespace: teckshop-prod
spec:
  secretStoreRefs:
    - name: teckshop-vault
      kind: SecretStore
  selector:
    secret:
      name: teckshop-rabbitmq-default-user
  refreshInterval: 30s
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: rabbitmq
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: rabbitmq
          property: password