# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - CSHARP_ROSLYNATOR
  - JSON_PRETTIER
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false
GITHUB_COMMENT_REPORTER: true
APPLY_FIXES_MODE: commit
CSHARP_DOTNET_FORMAT_ARGUMENTS: 'TeckShop.sln'
CSHARP_ROSLYNATOR_ARGUMENTS: 'TeckShop.sln'
VALIDATE_ALL_CODEBASE: false