
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teckshop-teck-dk
  namespace: teckshop-prod
spec:
  secretName: teckshop-teck-dk-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "teckshop.teck.dk"
  dnsNames:
  - "*.teckshop.teck.dk"
  - "teckshop.teck.dk"
