apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teckshop-ingress
  namespace: teckshop-prod
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.api.teckshop.teck.dk`)
      kind: Rule
      services:
        - name: yarp-gateway-service
          port: 8080
      middlewares:
      - name: headers
    - match: Host(`api.teckshop.teck.dk`)
      kind: Rule
      services:
        - name: yarp-gateway-service
          port: 8080
      middlewares:
      - name: headers
  tls:
    secretName: teckshop-teck-dk-production-tls
