apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teckshop-keycloak-secrets
  namespace: teckshop-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teckshop-vault
    kind: SecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: kv/keycloak
        property: secret