apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teckshop-postgres-secrets
  namespace: teckshop-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teckshop-vault
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/postgres
        property: password
    - secretKey: username
      remoteRef:
        key: kv/postgres
        property: username