apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teckshop-redis-secrets
  namespace: teckshop-prod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: teckshop-vault
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/redis
        property: password