apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: teckshop-prod
    name: in-cluster
  project: default
  source:
    path: deployment/helm/infrastructure/external-secret
    repoURL: git@github.com:CaptainPowerTurtle/TeckShop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true