apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination: 
    namespace: teckshop-prod
    name: in-cluster
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 20.1.5
    chart: redis
    helm: 
      releaseName: redis
      valueFiles: 
        - $values/deployment/helm/infrastructure/redis/values.yaml
  - repoURL: git@github.com:CaptainPowerTurtle/TeckShop.git
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true