name: Auto Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

permissions:
  contents: read # the config file
  issues: write # for labeling issues (on: issues)
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)
  statuses: write # to generate status
  checks: write # to generate status

jobs:
  auto-labeler:
    name: Auto Labeler
    runs-on:
      ubuntu-latest
      ## just for multi-labeler
      # statuses: write
      # checks: write

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0
      # - uses: release-drafter/release-drafter@v6
      #   with:
      #     config-name: release-drafter.yml
      #     disable-releaser: true # releaser mode is disabled.
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: fuxingloh/multi-labeler@v4.0.0
        name: conventional-commits-pull-request-labeler
        with:
          github-token: ${{secrets.GITHUB_TOKEN}} # optional, default to '${{ github.token }}'
          config-path: .github/multi-labeler.yml # optional, default to '.github/labeler.yml'
      - name: check-conventional-commits-labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        if: success()
        with:
          any_of: feature,bug,enhancement,refactor,deprecated,security,documentation,build,ci/cd,devops,chore,performance,formatting,dependencies,test,major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
